name: GitHub Actions Demo
on: 
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [coda-event]  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: 현재 디렉터리 위치 출력
        run: pwd
      - name: 현재 디렉터리 내용 출력
        run: ls -al
      - name: Check out repository code
        # {소유자}/{저장소명}@{참조자(버전)}
        uses: actions/checkout@v2
      - name: action 사용 후에 내용 출력
        run: ls -al
